//! HTML, BBCode and troff exports.

use crate::attr::{Attr, Color};
use crate::canvas::{Canvas, CACA_MAGIC_FULLWIDTH};
use crate::charset::utf32_is_fullwidth;

use super::push_utf8;

fn html_char(out: &mut String, ch: u32) {
    if ch == CACA_MAGIC_FULLWIDTH {
        // Fullwidth trailing cell: nothing to output.
    } else if ch <= 0x20 || (0x7f..=0xa0).contains(&ch) {
        out.push_str("&#160;");
    } else if ch == b'&' as u32 {
        out.push_str("&amp;");
    } else if ch == b'<' as u32 {
        out.push_str("&lt;");
    } else if ch == b'>' as u32 {
        out.push_str("&gt;");
    } else if ch == b'"' as u32 {
        out.push_str("&quot;");
    } else if ch == b'\'' as u32 {
        out.push_str("&#39;");
    } else if ch < 0x80 {
        out.push(ch as u8 as char);
    } else if ch <= 0x10fffd && (ch & 0xfffe) != 0xfffe && !(0xd800..=0xdfff).contains(&ch) {
        out.push_str(&format!("&#{};", ch));
    } else {
        out.push_str("&#65533;");
    }
}

pub(super) fn export_html(cv: &Canvas, html5: bool) -> Vec<u8> {
    let frame = cv.active();
    let width = frame.width;
    let height = frame.height;
    let mut out = String::new();

    if html5 {
        out.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        out.push_str("<meta charset=\"utf-8\" />\n");
    } else {
        out.push_str("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n");
        out.push_str("   \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
        out.push_str(
            "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">",
        );
        out.push_str("<head>\n");
    }

    out.push_str(&format!(
        "<title>Generated by libcaca {}</title>\n",
        Canvas::version()
    ));
    out.push_str("</head><body>\n");
    out.push_str("<div style=\"font-family: monospace, fixed; font-weight: bold;\">\n");

    for y in 0..height {
        let mut x = 0i32;

        while x < width {
            let attr = frame.attrs[(x + y * width) as usize];
            let a = Attr::from_raw(attr);

            out.push_str("<span style=\"");

            if a.to_ansi_fg() != Color::Default.as_u8() {
                out.push_str(&format!(";color:#{:03x}", a.to_rgb12_fg()));
            }
            if (a.to_ansi_bg() as u32) < 0x10 {
                out.push_str(&format!(";background-color:#{:03x}", a.to_rgb12_bg()));
            }
            if attr & 0x1 != 0 {
                out.push_str(";font-weight:bold");
            }
            if attr & 0x2 != 0 {
                out.push_str(";font-style:italic");
            }
            if attr & 0x4 != 0 {
                out.push_str(";text-decoration:underline");
            }
            if attr & 0x8 != 0 {
                out.push_str(";text-decoration:blink");
            }
            out.push_str("\">");

            let mut len = 0i32;
            while x + len < width && frame.attrs[(x + len + y * width) as usize] == attr {
                html_char(&mut out, frame.chars[(x + len + y * width) as usize]);
                len += 1;
            }

            out.push_str("</span>");
            x += len;
        }

        out.push_str("<br />\n");
    }

    out.push_str("</div></body></html>\n");

    out.into_bytes()
}

pub(super) fn export_html3(cv: &Canvas) -> Vec<u8> {
    let frame = cv.active();
    let width = frame.width;
    let height = frame.height;
    let stride = width;

    let mut boundary = vec![0u8; ((width + 7) / 8) as usize];
    let mut has_multi_cell_row = 0i32;

    let attrs = &frame.attrs;
    let chars = &frame.chars;
    let ansi_bg = |i: i32| Attr::from_raw(attrs[i as usize]).to_ansi_bg();
    let rgb24_bg = |i: i32| Attr::from_raw(attrs[i as usize]).to_rgb24_bg();
    let ansi_fg = |i: i32| Attr::from_raw(attrs[i as usize]).to_ansi_fg();
    let rgb24_fg = |i: i32| Attr::from_raw(attrs[i as usize]).to_rgb24_fg();

    for y in 0..height {
        for x in 1..width {
            let bit = boundary[(x / 8) as usize] & (1 << (x % 8));

            if bit == 0
                && (((chars[(x - 1 + y * stride) as usize] == CACA_MAGIC_FULLWIDTH)
                    && !utf32_is_fullwidth(chars[(x + y * stride) as usize]))
                    || ansi_bg(x - 1) != ansi_bg(x)
                    || (ansi_bg(x) < 0x10 && rgb24_bg(x - 1) != rgb24_bg(x)))
            {
                has_multi_cell_row = 1;
                boundary[(x / 8) as usize] |= 1 << (x % 8);
            }
        }
    }

    let mut out = String::new();
    out.push_str(
        "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" summary=\"[libcaca canvas export]\">\n",
    );

    for y in 0..height {
        out.push_str("<tr>");

        let mut x = 0i32;

        while x < width {
            let mut len = 1i32;

            while x + len < width {
                let chl = chars[(x + len + y * stride) as usize];
                let chlm1 = chars[(x + len - 1 + y * stride) as usize];

                let cond1 = (y != 0 && chl > 0x20 && !(0x7f..=0xa0).contains(&chl))
                    || (boundary[((x + len) / 8) as usize] & (1 << ((x + len) % 8)) == 0)
                    || chl == CACA_MAGIC_FULLWIDTH
                    || height == 1;
                let cond2 = chlm1 != CACA_MAGIC_FULLWIDTH || utf32_is_fullwidth(chl);
                let cond3 = ansi_bg(x + len) == ansi_bg(x);
                let cond4 = ansi_bg(x) >= 0x10 || rgb24_bg(x + len) == rgb24_bg(x);

                if cond1 && cond2 && cond3 && cond4 {
                    len += 1;
                } else {
                    break;
                }
            }

            let mut nonblank = 0i32;
            for i in 0..len {
                let c = chars[(x + i + y * stride) as usize];
                if !(c <= 0x20 || (0x7f..=0xa0).contains(&c)) {
                    nonblank = 1;
                }
            }

            out.push_str("<td");

            if ansi_bg(x) < 0x10 {
                out.push_str(&format!(" bgcolor=\"#{:06x}\"", rgb24_bg(x)));
            }

            if has_multi_cell_row != 0 && len > 1 {
                let mut colspan = len;

                for i in 0..len {
                    if i != 0
                        && (boundary[((x + i) / 8) as usize] & (1 << ((x + i) % 8))) == 0
                    {
                        colspan -= 1;
                    }
                }

                if colspan > 1 {
                    out.push_str(&format!(" colspan=\"{}\"", colspan));
                }
            }

            out.push('>');
            out.push_str("<tt>");

            let mut needfont = 0i32;

            for i in 0..len {
                let attr = attrs[(x + i + y * stride) as usize];

                if nonblank != 0 && (i == 0 || attr != attrs[(x + i - 1 + y * stride) as usize]) {
                    needfont = if ansi_fg(x + i) != Color::Default.as_u8() {
                        1
                    } else {
                        0
                    };

                    if needfont != 0 {
                        out.push_str(&format!("<font color=\"#{:06x}\">", rgb24_fg(x + i)));
                    }
                    if attr & 0x1 != 0 {
                        out.push_str("<b>");
                    }
                    if attr & 0x2 != 0 {
                        out.push_str("<i>");
                    }
                    if attr & 0x4 != 0 {
                        out.push_str("<u>");
                    }
                    if attr & 0x8 != 0 {
                        out.push_str("<blink>");
                    }
                }

                html_char(&mut out, chars[(x + i + y * stride) as usize]);

                if nonblank != 0
                    && ((i + 1) == len
                        || attr != attrs[(x + i + 1 + y * stride) as usize])
                {
                    if attr & 0x8 != 0 {
                        out.push_str("</blink>");
                    }
                    if attr & 0x4 != 0 {
                        out.push_str("</u>");
                    }
                    if attr & 0x2 != 0 {
                        out.push_str("</i>");
                    }
                    if attr & 0x1 != 0 {
                        out.push_str("</b>");
                    }
                    if needfont != 0 {
                        out.push_str("</font>");
                    }
                }
            }

            out.push_str("</tt>");
            out.push_str("</td>");

            x += len;
        }

        out.push_str("</tr>\n");
    }

    out.push_str("</table>\n");

    out.into_bytes()
}

pub(super) fn export_bbfr(cv: &Canvas) -> Vec<u8> {
    let frame = cv.active();
    let width = frame.width;
    let height = frame.height;
    let stride = width;

    let attrs = &frame.attrs;
    let chars = &frame.chars;
    let ansi_bg = |i: i32| Attr::from_raw(attrs[i as usize]).to_ansi_bg();
    let ansi_fg = |i: i32| Attr::from_raw(attrs[i as usize]).to_ansi_fg();
    let rgb24_bg = |i: i32| Attr::from_raw(attrs[i as usize]).to_rgb24_bg();
    let rgb24_fg = |i: i32| Attr::from_raw(attrs[i as usize]).to_rgb24_fg();

    let mut out: Vec<u8> = Vec::new();
    out.extend_from_slice(b"[font=Courier New]");

    for y in 0..height {
        let mut x = 0i32;

        while x < width {
            let mut len = 1i32;

            if chars[(x + y * stride) as usize] == b' ' as u32 {
                while x + len < width
                    && attrs[(x + len + y * stride) as usize] == attrs[(x + y * stride) as usize]
                    && chars[(x + y * stride) as usize] == b' ' as u32
                {
                    len += 1;
                }
            } else {
                while x + len < width
                    && attrs[(x + len + y * stride) as usize] == attrs[(x + y * stride) as usize]
                    && chars[(x + y * stride) as usize] != b' ' as u32
                {
                    len += 1;
                }
            }

            let needback = ansi_bg(x) < 0x10;
            let needfront = ansi_fg(x) < 0x10;

            if needback {
                out.extend_from_slice(format!("[f=#{:06x}]", rgb24_bg(x)).as_bytes());
            }

            if chars[(x + y * stride) as usize] == b' ' as u32 {
                out.extend_from_slice(format!("[c=#{:06x}]", rgb24_bg(x)).as_bytes());
            } else if needfront {
                out.extend_from_slice(format!("[c=#{:06x}]", rgb24_fg(x)).as_bytes());
            }

            let start_attr = attrs[(x + y * stride) as usize];
            if start_attr & 0x1 != 0 {
                out.extend_from_slice(b"[g]");
            }
            if start_attr & 0x2 != 0 {
                out.extend_from_slice(b"[i]");
            }
            if start_attr & 0x4 != 0 {
                out.extend_from_slice(b"[s]");
            }

            for i in 0..len {
                let ch = chars[(x + i + y * stride) as usize];

                if ch == CACA_MAGIC_FULLWIDTH {
                    // nothing
                } else if ch == b' ' as u32 {
                    out.push(b'_');
                } else {
                    push_utf8(&mut out, ch);
                }
            }

            if start_attr & 0x4 != 0 {
                out.extend_from_slice(b"[/s]");
            }
            if start_attr & 0x2 != 0 {
                out.extend_from_slice(b"[/i]");
            }
            if start_attr & 0x1 != 0 {
                out.extend_from_slice(b"[/g]");
            }

            if chars[(x + y * stride) as usize] == b' ' as u32 || needfront {
                out.extend_from_slice(b"[/c]");
            }
            if needback {
                out.extend_from_slice(b"[/f]");
            }

            x += len;
        }

        out.push(b'\n');
    }

    out.extend_from_slice(b"[/font]\n");
    out
}

pub(super) fn export_troff(cv: &Canvas) -> Vec<u8> {
    const ANSI2TROFF: [&str; 16] = [
        "black", "blue", "green", "cyan", "red", "magenta", "yellow", "white", "black", "blue",
        "green", "cyan", "red", "magenta", "yellow", "white",
    ];

    let frame = cv.active();
    let width = frame.width;
    let height = frame.height;
    let stride = width;

    let mut out: Vec<u8> = Vec::new();
    out.extend_from_slice(b".nf\n");

    let mut prevfg = 0u32;
    let mut prevbg = 0u32;
    let mut started = false;

    for y in 0..height {
        for x in 0..width {
            let idx = (x + y * stride) as usize;
            let attr = Attr::from_raw(frame.attrs[idx]);
            let fg = attr.to_ansi_fg();
            let bg = attr.to_ansi_bg();
            let ch = frame.chars[idx];

            if fg != prevfg as u8 || !started {
                let name = ANSI2TROFF.get(fg as usize).copied().unwrap_or("white");
                out.extend_from_slice(format!("\\m[{}]", name).as_bytes());
            }
            if bg != prevbg as u8 || !started {
                let name = ANSI2TROFF.get(bg as usize).copied().unwrap_or("black");
                out.extend_from_slice(format!("\\M[{}]", name).as_bytes());
            }
            if attr.raw() & 0x1 != 0 {
                out.extend_from_slice(b"\\fB");
            }
            if attr.raw() & 0x2 != 0 {
                out.extend_from_slice(b"\\fI");
            }

            if ch == b'\\' as u32 {
                out.extend_from_slice(b"\\\\");
            } else if ch == b' ' as u32 {
                if x == 0 || x == width - 1 {
                    out.push(0xc2);
                    out.push(0xa0);
                } else {
                    push_utf8(&mut out, ch);
                }
            } else {
                push_utf8(&mut out, ch);
            }

            if attr.raw() & 0x3 != 0 {
                out.extend_from_slice(b"\\fR");
            }

            prevfg = fg as u32;
            prevbg = bg as u32;
            started = true;
        }

        out.push(b'\n');
    }

    out
}
